### ISSUE TITLE
tmux 2.9 

### ISSUE THREAD

**Issue by belarbi2733** [Amine27/dotfiles#1]
need some changes for tmux 2.9

**Comment by Amine27** [comment]
@belarbi2733 Can you tell the changes please ?
Thank you.

**Comment by belarbi2733** [comment]
error in line 8 & 9 & 23 & 24
line 8 & 9 will be : set -g pane-border-style bg=default,fg=colour244
line 23 & 24 will be : setw -g window-status-current-style bg=red,fg=white
